### ISSUE TITLE
AREMP AvgBFWDratio calculation not needed in CombineData.R code?

### ISSUE THREAD

**Issue by ghost** [rascully/Stream-Monitoring-Data-Exchange-Specifications#20]
### Re the two lines of code below:
`    # Calculate the AREMP bankful width to depth ratio `
from https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/d646f574c5b4192262bae0ff02a0bd8167472227/DataIntegrationExample/R/CombineData.R#L218

`    data$ave_widthDepth_ratio    <- data$average_bfwidth / data$average_bfdepth`
from
https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/d646f574c5b4192262bae0ff02a0bd8167472227/DataIntegrationExample/R/CombineData.R#L219

Question: Why is this being calculated when AREMP has a field for this: 'ave_widthDepth_ratio'? 

Comment: It may be a remnant from when we split the AvgBFWDRAtio and AvgBFWDRatioStreambed. The data mapping has been updated to include AREMP and PIBO's AvgBFWDratio and removed AIM and EPA's. 

Action to take: I believe these 2 lines of code need to be removed to reflect those changes.

**Comment by eheaston** [comment]
Actually we need to keep AvgBFWDratio calculation for AREMP data.
Double check that the calculation in code is correct. If not it needs to be updated.

**Comment by ghost** [comment]
after group chat, decision to keep the calculation in as-is.

**follow up to do:** (@edlabo ) 
Make sure calculation is well documented for users.
Confirm how PIBO calculates avgBFWDratio - is it same? (calculating transect by transect, then calculating average to get avg across reach)

**Comment by ghost** [comment]
PIBO calculates AvgBFWDRatio proper transect by transect way - not same as aremp.

how do we want to proceed? (ask Tues group)

**Comment by ghost** [comment]
group decided this difference between PIBO and AREMP is ok so long as calculations are sufficiently documented.
Leave AREMP calculation in code as-is and close this issue.
