### ISSUE TITLE
Resolve generation of unique IDs not remaining static w/ each code run CombineData.R

### ISSUE THREAD

**Issue by ghost** [rascully/Stream-Monitoring-Data-Exchange-Specifications#21]
Line in code where issue originates:
https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/d646f574c5b4192262bae0ff02a0bd8167472227/DataIntegrationExample/R/CombineData.R#L373

**Issue:** The Unique IDs generated (datasetID, eventID, locationID, measurementTypeID) are currently being reproduced each time the code re-runs. The generated UIDs need to be static in order to function properly as UIDs.

**Action to take:** correct code so that when altering or adding new data, if a UID already exists or has been generated, the code bypasses it and only creates UIDs for new rows of data

**Comment by ghost** [comment]
locationIDs are currently showing 454 duplicate IDs, which causes problems when trying to use locationID as the primary key in a database. need to resolve via code either by generating locationIDs based on different criteria, eliminating duplicate rows, or adding a suffix to the locationID to correct duplication. list of duplicate locationIDs attached.

[20220919_duplicates_location.txt](https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/files/9602357/20220919_duplicates_location.txt)

**Comment by ghost** [comment]
> locationIDs are currently showing 454 duplicate IDs, which causes problems when trying to use locationID as the primary key in a database. need to resolve via code either by generating locationIDs based on different criteria, eliminating duplicate rows, or adding a suffix to the locationID to correct duplication. list of duplicate locationIDs attached.
> 
> [20220919_duplicates_location.txt](https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/files/9602357/20220919_duplicates_location.txt)


this is related to the AIM duplicate locations, I think. I haven't fully explored the duplicates to confirm that yet and these duplicates are from an older version of the dataset now that the code has been re-run.

regardless, there may be duplicate AIM locations where we want to choose only the FIRST visit location - based on the AIM Field “**FieldEvalDate**”

**Comment by eheaston** [comment]
Fixed the duplicate ID's issue.
