### ISSUE TITLE
Unit conversion needed: MeanThalwegDepth

### ISSUE THREAD

**Issue by ghost** [rascully/Stream-Monitoring-Data-Exchange-Specifications#22]
Add to either CombineData.R file or the pre-processing EPA NRSA code file.

**Issue:** NRSA MeanThalwegDepths are measured in centimeters (values range from 1.25 - 268.1). This does not meet standard requirements. AIM are measured in meters (values range from 0 - 2.1) and the data exchange standard requires meters.

**Action to take:** add mathematical conversion from centimeters to meters for all NRSA XDEPTH_CM values

**Comment by eheaston** [comment]
@eheaston added code to the CombineData.R script to convert MeanThalwegDepth from cm to m

Added code reads:
#Converting NRSA MeanThalwegDepth data from cm to m - EH added
all_data2 <- all_data2 %>%
  mutate(MeanThalwegDepth = ifelse(projectCode == "NRSA", MeanThalwegDepth/100, MeanThalwegDepth))
