### ISSUE TITLE
Unit conversion needed: D50

### ISSUE THREAD

**Issue by ghost** [rascully/Stream-Monitoring-Data-Exchange-Specifications#23]
Add to CombineData.R file for PIBO?

**Issue:** PIBO D50 are measured using meters (values range from 0.002 - 0.5025). The data standard requires millimeters and AIM measures millimeters (values range from 1 - 4098). Units must match AIM and data standard.

**Action to take:** add mathematical conversion from meters to millimeters for all PIBO D50 values

**Note:** PIBO D16 and D84 are also compatible but the data is not currently included. If added later, these values will also need to be converted from m to mm.

**Comment by eheaston** [comment]
@eheaston fixed this buy adding code in the CombineData.R script to covert PIBO D50 data from m to mm.
Also converted D50 to an integer from numeric field type, to be consistent with the other substrate attributes (D16 & D84)

Added code reads:
#Converting PIBO D50 data from m to mm - EH added
all_data2 <- all_data2 %>% 
  mutate(D50 = as.integer(ifelse(projectCode =="PIBO", D50*1000, D50)))
