### ISSUE TITLE
RecordLevel table formatting

### ISSUE THREAD

**Issue by ghost** [rascully/Stream-Monitoring-Data-Exchange-Specifications#28]
**Location in code:** I think it starts here:
https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/073e8fffcec429eac8d7b22d29c56b200362e4ef/DataIntegrationExample/R/CombineData.R#L268

**Issue in dataset:** https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/master/DataIntegrationExample/data/csv/RecordLevel.csv

**Issue:** The formatting of the RecordLevel table has gone a bit funky. Not quite sure how this happened.

**Action to take:**
Modify code so output RecordLevel table looks more like this: https://github.com/edlabo/Stream-DES-feedback-updates/blob/master/DataIntegrationExample/data/csv/RecordLevel_cleaned.csv

I attempted to make minor changes to the code here (https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/master/DataIntegrationExample/R/CombineData.R) to correct this, but need to ensure a) it fixes it and b) I didn't break anything when the code runs.

**Comment by ghost** [comment]
Formatting is fixed!

2 new issues arose: 

1. EPA NRSA lost it's datasetID number, which is now showing as "NA"
-- not sure about this one. 

3. duplicated rows for BLM AIM and PIBO  
-- this is likely related to how the former table had multiple samplingProtocols, and changed when we revised the samplingProtocol category to contain MR.org links

**Comment by ghost** [comment]
> Formatting is fixed!
> 
> 2 new issues arose:
> 
> 1. EPA NRSA lost it's datasetID number, which is now showing as "NA"
>    -- not sure about this one.
> 2. duplicated rows for BLM AIM and PIBO
>    -- this is likely related to how the former table had multiple samplingProtocols, and changed when we revised the samplingProtocol category to contain MR.org links

1) still to do
2) is done

+ 3) also update AREMP's **datasetLink**
 to https://www.fs.usda.gov/r6/reo/monitoring/downloads/watershed/NwfpWatershedCondition20yrReport.gdb.zip
and AREMP's **metadataID** to
https://www.fs.usda.gov/r6/reo/monitoring/downloads/watershed/NwfpWatershedCondition20yrReport.gdb.htm

**Comment by eheaston** [comment]
1. Should have been fixed with the 4/28 pull request from the emily-branch.
ConbineData.R script code has been modified to assign NRSA the datasetID '4'
